### ISSUE TITLE
Make logging optional

### ISSUE THREAD

**Issue by jsdf** [rotundasoftware/parcelify#10]
Currently parcelify prints out stuff to the standard streams via npmlog, with no option (that I'm aware of) to suppress it. That's fine when it's being run as a command, but for API use it would really be best if API consumers were able to attach their own logging instead. 

Ideally that would mean that events would just be proxied to the parcelify instance, and logging only attached in `cmd.js`, but even just the option to supress logging would help (though kind of ugly, API wise).

I'm happy to put together a PR, just wanted to know which option would be preferred.

**Comment by substack** [comment]
http://www.faqs.org/docs/artu/ch01s06.html#id2878450 is a good rule of thumb here. It's much easier to enable a feature than to disable one.

**Comment by dgbeck** [comment]
Hard to take issue with that logic!

We should be good here.. this change was made in #11 and default logLevel is 'warn' so only important things should be showing up.
