### ISSUE TITLE
Concatenate all found sass files and then compile

### ISSUE THREAD

**Issue by johanneslumpe** [rotundasoftware/parcelify#14]
Given the following situation:
- A module has some base scss, including a settings file
- The module has several plugins, which contain scss files, which need to be able to access variables provided in the parent module's settings file

Is is possible to achieve this with parcelify? Right now it looks like that it compiles each set of files on its own, which makes defined variables from other modules inaccessible.

From the top of my head I'd assume that for something like this a temporary scss file, which imports all scss files from the project's root directory with their full path (`node_modules/module/some/file.scss`) so that sass can correctly process their imports, has to be created. This file would then be compile-able and all variables would be available. Is there anything like this built into parcelify or is this use case way too specific?

**Comment by majgis** [comment]
@johanneslumpe I would like to see what you came up with, if you are willing to publish to github and a gist is fine too.  I am dealing with this same problem at the moment.  The method I had envisioned was to use npm link to share a common resource across packages, keeping the isolation of the package intact, but I have yet to inspect the output from parcelify and I would like to compare against your solution.  Thanks!

**Comment by johanneslumpe** [comment]
@dgbeck @majgis I just published a version, albeit without tests: https://www.npmjs.com/package/parcelify-import-resolver

**Comment by dgbeck** [comment]
Cool! Thanks for sharing!
