### ISSUE TITLE
API for source maps

### ISSUE THREAD

**Issue by cowwoc** [rotundasoftware/parcelify#19]
The command-line lists `--maps, -m        Enable JavaScript source maps in js bundles (for dev mode).` but the API documentation does not provide an equivalent option.

**Comment by dgbeck** [comment]
Hi @cowwoc , the deal is that this option can be set through the API using. Providing a separate option via the API would be redundant.

```
browserifyBundleOptions : {
	debug : maps
}
```

I just added a reference to this use case in the docs for `browserifyBundleOptions`. Thx!
