### ISSUE TITLE
Mixing parcelify and factor-bundle?

### ISSUE THREAD

**Issue by cowwoc** [rotundasoftware/parcelify#20]
Hi David,

It is my understanding that right now `parcelify` only creates isolated modules and does not create a common-code bundle.

https://github.com/substack/factor-bundle allows one to create entry-specific and common bundles. Is it possible to do the same with `parcelify` or actually using `factor-bundle` with this plugin?

**Comment by dgbeck** [comment]
Hi @cowwoc!

We have not given any special consideration to compatibility with factor-bundle. However there are a couple of ways to go about factoring out common assets:

1. By passing in your own browserify instance (via the `browserifyInstance` option), you can specify that files in your common bundle are external when compiling your other bundles. See [this issue](https://github.com/rotundasoftware/cartero/pull/28) on the cartero repo for a discussion and example of this approach.

2. If your concern is primarily factoring out common js assets, then when compiling production assets, you can simply run browserify first with factor-bundle, and then run parcelify just for the css assets.

Hope that helps! Closing for now, but we keep this on our radar for the future.

**Comment by cowwoc** [comment]
I love the idea of running browserify first, and then running parcelify just for the css assets (great for separation of concerns). How would I do this from an API perspective? What would the code look like?

Thanks!

**Comment by cowwoc** [comment]
@dgbeck Can we please reopen this issue until we have a concrete example to point to (even if only in the issue tracker)?

I went with option 2 by doing the following:

1. Ran browserify with factor-bundle.
2. Ran parcelify, passing the output from step 1 as the `mainPath` constructor argument.

Here is where you run into problems...

If `mainPath` references `Common.js` (code shared by all partitions in step 1) and `Common.js` contains http://medialize.github.io/URI.js/ then parcelify fails with:

```
Error: Error while browserifying "./target/classes/../factor-bundle/com/realestate/frontend/page/Common.js":Error: module "./punycode" not found from "C:\\Users\\Gili\\Documents\\realestate\\frontend\\target\\factor-bundle\\com\\realestate\\frontend\\page\\Common.js"
    at Stream.<anonymous> (C:\Users\Gili\Documents\realestate\frontend\node_modules\parcelify\index.js:141:35)
    at Stream.<anonymous> (C:\Users\Gili\Documents\realestate\frontend\node_modules\parcelify\node_modules\browserify\index.js:323:22)
    at Stream.<anonymous> (C:\Users\Gili\Documents\realestate\frontend\node_modules\parcelify\node_modules\browserify\index.js:323:22)
    at Stream.emit (events.js:117:20)
    at Transform.emit (events.js:117:20)
    at Stream.emit (events.js:117:20)
    at f (C:\Users\Gili\Documents\realestate\frontend\node_modules\parcelify\node_modules\browserify\node_modules\module-deps\index.js:127:36)
    at C:\Users\Gili\Documents\realestate\frontend\node_modules\parcelify\node_modules\browserify\index.js:731:20
    at C:\Users\Gili\Documents\realestate\frontend\node_modules\parcelify\node_modules\browserify\node_modules\browser-resolve\index.js:185:24
    at C:\Users\Gili\Documents\realestate\frontend\node_modules\parcelify\node_modules\resolve\lib\async.js:36:22
```

Why? Because step 1 dumped both `URI.js` and `punycode.js` into `Common.js` but now that parcelify is running, it has no idea that `./punycode` is already inside `Common.js`.

Any ideas?

**Comment by dgbeck** [comment]
Hi @cowwoc , so it sounds like the issue may be that parcelify should be run on the same javascript entry point that browserify was run on... not the output from browserify. See [this article](https://gist.github.com/substack/68f8d502be42d5cd4942#parcelify) for an example. Does that do it for you?

**Comment by cowwoc** [comment]
@dgbeck Excuse my ignorance then: what is the benefit of enabling parcelify's Javascript output (as opposed to only outputting CSS files)? Is there any difference between running:

```
browserify input.js > output.js
parcelify input.js -j output.js -c output.css
```

and

```
browserify input.js > output.js
parcelify input.js -c output.css
```

Or do they result in identical output/behavior?

**Comment by dgbeck** [comment]
> what is the benefit of enabling parcelify's Javascript output (as opposed to only outputting CSS files)

The only benefit is performance. parcelify uses the js dependency graph in order to do its job of building the css bundle. The way gets the dependency graph is to run browserify on the supplied entry point and listen for the events that browserify generates. So when parcelify is done, browserify has already run through all its paces, and it costs virtually nothing to just dump the output generated by browserify into a js bundle. Running browserify separate from parcelify means the js bundle has to be generated twice.

**Comment by cowwoc** [comment]
Got it. Thanks for the clarification. On a sidenote, I agree that refactoring parceilify as a browserify plugin would clean up the architecture.
