### ISSUE TITLE
`bundleWritten` not emitted in watch mode?

### ISSUE THREAD

**Issue by alessioalex** [rotundasoftware/parcelify#33]
Hey @dgbeck I'm trying to determine when the bundle has been written to disk, but it seems that neither the `done` event or `bundleWritten` events are being emitted when that happens if `watch` mode is enabled.

Is this by design or is it a bug? Also, is there another way to determine this? Tnx

**Comment by dgbeck** [comment]
Hi @alessioalex this should be resolved in #34 . Closing here, can pick discussion on #34 if it is still an issue. Thanks!
