### ISSUE TITLE
Parcelify on a no-javascript package?

### ISSUE THREAD

**Issue by poonwu** [rotundasoftware/parcelify#40]
If I include a package with no javascript such as 
```
npm install font-awesome
```

```
require('font-awesome');
```

and tried to browserify the package with parcelify plugin, the browserify exit with a "cannot find module" error. I tried to set `ignoreMissing`, but the result is basically an empty result (no bundled script and no bundled css whatsoever). Does parcelify support no-javascript package?

**Comment by dgbeck** [comment]
Hi @poonwu ! The short answer is no.. more thorough answer & reasoning is in #28.

Thanks!
