### ISSUE TITLE
Is any way to pass options to transform (package.json)?

### ISSUE THREAD

**Issue by mt0erfztxt** [rotundasoftware/parcelify#42]
I am wrote simple transform stream for Stylus to CSS transformation to use with Parcelify and it works, but can't find a way to pass options to it! Tried to use it as in docs for [module-deps](https://github.com/substack/module-deps#packagejson-transformkey):
```javascript
{
...
  "transforms": { // Must be an Array as per Parcelify docs, I know.
    "stylus-css-stream": [["fff", { "x": 3 }], ["ggg", { "y": 4 }]]
  }
}
```
, but transform simply ignored and in 'bundle.css' I have 'style.styl' as-is.

Maybe someone already faced such necessity and found a solution?

**Comment by mt0erfztxt** [comment]
No matter any more (as decide to compile Stylus to CSS in module and drop "transforms" at all).

**Comment by dgbeck** [comment]
See #29, please search before opening issues. Thx!

**Comment by mt0erfztxt** [comment]
Ok. Thanks for reply!
