### ISSUE TITLE
parcelify should output a directory and copy assets

### ISSUE THREAD

**Issue by jxe** [rotundasoftware/parcelify#43]
I really like parcelify but there are aspects of the design I'm not sure of, namely that it:

* totally breaks all css with assets, by default
* requires modules which needn't know anything about it to have a "transforms" key which references its own special internal packages
* because the default flow outputs a single .css file, it suggests inlining things which shouldn't be inlined

It seems to me these are all easy to fix but it's a major change to parcelify.  I plan to modify parcelify so that it takes a directory to output assets and css to, not a single file, and so that it copies urls() over into hashed filenames by default.

What should I call this modified parcelify? parcelify3? joes-special-parcelify?

**Comment by dgbeck** [comment]
Hi @jxe !

Thanks for your interest!

I'm not totally clear on what your needs are, but sounds like you might be looking for a more complete asset solution, in which case take a look at [cartero](https://github.com/rotundasoftware/cartero), as it can handle images, etc.

If that's not what you're after and you do end up forking, feel free to name your fork whatever you think is most appropriate.

I'm going to close this ticket, as I'm not clear on the specifics of the issues, but if you'd like to discuss  further let's open individual issues, and go into more details, with examples, so we can better understand your needs and your ideas on how to address them. In the best case there will be some ways to address your needs with the current version that we can point you towards.

Thx!
