### ISSUE TITLE
Can't pass options to transforms

### ISSUE THREAD

**Issue by gryphonmyers** [rotundasoftware/parcelify#44]
There doesn't seem to be any way to pass options to parcelify transforms, yet the transforms themselves seem to support options (e.g., sass transform accepts options, which it passes to the sass compiler).

Am I missing something or is this currently impossible? The way I envision it, you should be able to pass arrays to the appTransforms options, with the first item in the array being the name and the second being an options object (I have seen this pattern in use elsewhere). This would then cause all submodules to run the transform with those options. The problem I'm currently having is I need my sass @import statements to find modules located in my bower_components folder - node-sass accepts an "includePaths" option - I just need to get it there!

I desperately need this feature and will write it if you are on board with it and can give it a bit of guidance through your code. Thanks.

**Comment by dgbeck** [comment]
Hi @gryphonmyers ! Please see https://github.com/rotundasoftware/parcelify/issues/29 ! Closing for now but let us know if that doesn't work for you.
